name: notifica-saude-frontend

services:
  frontend:
    build:
      context: .
      args:
        VITE_API_URL: ${VITE_API_URL}
    env_file:
      - path: .env
        required: true
    ports:
      - "5179:5173"