events {

}

http {
    include /etc/nginx/mime.types;

    server {

        listen 5173;
        server_name nes-server.equipe4.front.facom.ufms.br;
        root /usr/share/nginx/html;
        index index.html;

        location / {
            # Check if the requested URI exists as a file or directory.
            # If not, serve index.html to allow client-side routing.
            try_files $uri $uri/ /index.html;
            
        }

    }

}
